[TM-1386] update reports statuses
wri/wri-terramatch-api pull request #534
Opened 2024-10-31 15:52 UTC by egrojMonroy

This is a seeder that will update via projects projectReport, siteReport and tasks from 
“awaiting approval” or “needs more information” to “approved”.

php artisan db:seed --class=UpdateProjectStatusSeeder

2024-10-31 15:56 UTC, cesarLima1 approved these changes

2024-10-31 17:48 UTC, roguenet requested changes
Two thing:
* This would be better implemented as a Command than a seeder, as it more conceptually aligns with what this tool is doing. Seeders are for getting initial data into a table, not for modifications
* I don't think the .csv makes much sense to check in. Would be better to just upload to the EC2 box and pass it as an argument to the command. 

`BulkWorkdayImport` is an example of a Command that works in this way.

2024-11-01 21:59 UTC, roguenet reviewed
the command looks good, but please remove the seeder and checked in .csv.

2024-11-04 18:30 UTC, roguenet approved these changes

2024-11-04 21:58 UTC, merged